"""update students's table schema

Revision ID: 2470627663a1
Revises: 653d4b3ced15
Create Date: 2024-12-04 22:11:23.747893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2470627663a1'
down_revision: Union[str, None] = '653d4b3ced15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('degree_program_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'degree_programs', ['degree_program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'degree_program_id')
    # ### end Alembic commands ###
