"""update teacher's table schema

Revision ID: 846cab1eb56f
Revises: 
Create Date: 2024-12-04 20:26:12.901908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846cab1eb56f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('department_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('teacher_type', sa.String(), nullable=False))
    op.drop_constraint('teachers_department_id_fkey', 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'departments', ['department_name'], ['name'])
    op.drop_column('teachers', 'hashed_password')
    op.drop_column('teachers', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key('teachers_department_id_fkey', 'teachers', 'departments', ['department_id'], ['id'])
    op.drop_column('teachers', 'teacher_type')
    op.drop_column('teachers', 'department_name')
    # ### end Alembic commands ###
