"""update students's table schema

Revision ID: cad6beb7e7ce
Revises: 846cab1eb56f
Create Date: 2024-12-04 21:01:47.931908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad6beb7e7ce'
down_revision: Union[str, None] = '846cab1eb56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_email', sa.String(), nullable=False))
    op.drop_index('ix_students_email', table_name='students')
    op.create_index(op.f('ix_students_student_email'), 'students', ['student_email'], unique=True)
    op.drop_constraint('students_degree_program_name_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'email')
    op.drop_column('students', 'degree_program_name')
    op.add_column('teachers', sa.Column('teacher_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('teacher_email', sa.String(), nullable=False))
    op.drop_index('ix_teachers_email', table_name='teachers')
    op.drop_index('ix_teachers_name', table_name='teachers')
    op.create_index(op.f('ix_teachers_teacher_email'), 'teachers', ['teacher_email'], unique=True)
    op.create_index(op.f('ix_teachers_teacher_name'), 'teachers', ['teacher_name'], unique=False)
    op.drop_column('teachers', 'name')
    op.drop_column('teachers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teachers_teacher_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_teacher_email'), table_name='teachers')
    op.create_index('ix_teachers_name', 'teachers', ['name'], unique=False)
    op.create_index('ix_teachers_email', 'teachers', ['email'], unique=True)
    op.drop_column('teachers', 'teacher_email')
    op.drop_column('teachers', 'teacher_name')
    op.add_column('students', sa.Column('degree_program_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('students_degree_program_name_fkey', 'students', 'degree_programs', ['degree_program_name'], ['name'])
    op.drop_index(op.f('ix_students_student_email'), table_name='students')
    op.create_index('ix_students_email', 'students', ['email'], unique=True)
    op.drop_column('students', 'student_email')
    # ### end Alembic commands ###
