# Generated by Django 5.1.4 on 2025-01-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree_program_name',
        ),
        migrations.AddField(
            model_name='student',
            name='degree_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='backend.degreeprogram'),
        ),
    ]
