# Generated by Django 5.1.4 on 2025-01-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_student_degree_program_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_id',
        ),
        migrations.CreateModel(
            name='TeacherPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_details', to='backend.teachers')),
            ],
        ),
    ]
