# Generated by Django 5.1.4 on 2025-01-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_teachers_teacher_id_teacherpasswords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='backend.teachers'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='degree_programs',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='backend.degreeprogram'),
        ),
    ]
