# Generated by Django 5.1.4 on 2025-01-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_course_teacher_teachers_degree_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='degree_programs',
        ),
        migrations.AddField(
            model_name='teachers',
            name='degree_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='backend.degreeprogram'),
        ),
    ]
