# Generated by Django 5.1.4 on 2025-01-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_schedule_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='courses',
            field=models.ManyToManyField(related_name='instructors', to='backend.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to='backend.teachers'),
        ),
    ]
