# Generated by Django 5.1.4 on 2025-01-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_teachers_courses_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_program',
            new_name='degree_program',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
    ]
