# Generated by Django 5.1.4 on 2025-01-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_course_program_course_degree_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='courses',
        ),
        migrations.AddField(
            model_name='teachers',
            name='teaching_type',
            field=models.CharField(blank=True, default='visitor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='backend.teachers'),
        ),
    ]
