# Generated by Django 5.1.4 on 2025-01-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_remove_teachers_courses_teachers_teaching_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="schedule",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Lecture",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
