# Generated by Django 5.1.4 on 2025-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_generatedschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.IntegerField(default=1),
        ),
    ]
