# Generated by Django 5.1.4 on 2025-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedschedule',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
