# Generated by Django 5.1.4 on 2025-05-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teachertoken",
            old_name="student",
            new_name="teacher",
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("semester", models.CharField(blank=True, max_length=20, null=True)),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "degree_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="backend.degreeprogram",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teachers",
                    ),
                ),
            ],
        ),
    ]
