# Generated by Django 5.1.4 on 2025-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_rename_student_teachertoken_teacher_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="room_name",
        ),
        migrations.AddField(
            model_name="classroom",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
