# Generated by Django 5.1.4 on 2025-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_remove_classroom_room_name_classroom_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="semester",
            field=models.IntegerField(default=1),
        ),
    ]
