# Generated by Django 5.1.4 on 2025-05-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_alter_student_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances_schedule",
                to="backend.generatedschedule",
            ),
        ),
    ]
