# Generated by Django 5.1.4 on 2025-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_attendance_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
