# Generated by Django 5.1.4 on 2025-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_alter_classroom_latitude_alter_classroom_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="semester",
            field=models.IntegerField(default=1),
        ),
    ]
